import { MigrationInterface, QueryRunner } from "typeorm";

export class FullSchema1772568385126 implements MigrationInterface {
    name = 'FullSchema1772568385126'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "unidades" DROP CONSTRAINT "fk_unidades_unidad_medida"`);
        await queryRunner.query(`ALTER TABLE "unidades" DROP CONSTRAINT "fk_unidades_caracteristica"`);
        await queryRunner.query(`ALTER TABLE "unidades" DROP CONSTRAINT "fk_unidades_inventario"`);
        await queryRunner.query(`ALTER TABLE "unidades" DROP CONSTRAINT "unidades_fk_lote_fkey"`);
        await queryRunner.query(`ALTER TABLE "rutas" DROP CONSTRAINT "rutas_fk_modulo_fkey"`);
        await queryRunner.query(`ALTER TABLE "permisos" DROP CONSTRAINT "permisos_fk_ruta_fkey"`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" DROP CONSTRAINT "rol_permiso_fk_rol_fkey"`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" DROP CONSTRAINT "rol_permiso_fk_permiso_fkey"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP CONSTRAINT "notificaciones_fk_usuario_fkey"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_fk_rol_fkey"`);
        await queryRunner.query(`ALTER TABLE "movimientos" DROP CONSTRAINT "movimientos_fk_unidad_fkey"`);
        await queryRunner.query(`ALTER TABLE "movimientos" DROP CONSTRAINT "movimientos_fk_usuario_fkey"`);
        await queryRunner.query(`ALTER TABLE "movimientos" DROP CONSTRAINT "movimientos_fk_lote_fkey"`);
        await queryRunner.query(`ALTER TABLE "lote_materia_prima" DROP CONSTRAINT "lote_materia_prima_fk_materia_prima_fkey"`);
        await queryRunner.query(`ALTER TABLE "lote_materia_prima" DROP CONSTRAINT "lote_materia_prima_fk_lote_fkey"`);
        await queryRunner.query(`ALTER TABLE "materias_primas" DROP CONSTRAINT "materias_primas_fk_unidad_medida_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_unidades_fk_lote"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rutas_fk_modulo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_permisos_fk_ruta"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rol_permiso_fk_rol"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rol_permiso_fk_permiso"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notificaciones_fk_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_fk_rol"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movimientos_fk_lote"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lote_materia_prima_fk_lote"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lote_materia_prima_fk_materia_prima"`);
        await queryRunner.query(`ALTER TABLE "inventarios" ALTER COLUMN "estado" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventarios" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventarios" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "caracteristicas" ALTER COLUMN "estado" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "caracteristicas" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "caracteristicas" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modulos" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modulos" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rutas" ALTER COLUMN "listed" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "rutas" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rutas" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permisos" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permisos" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "leido" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "requiere_accion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_vendida" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_degustacion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_alianza" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_total" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_inventario" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lotes" ALTER COLUMN "cantidad_unidades" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "unidades_medida" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "unidades_medida" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "unidades" ADD CONSTRAINT "FK_e78facb89f7e11b9f8b7aab9b6a" FOREIGN KEY ("fk_inventario") REFERENCES "inventarios"("id_inventario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidades" ADD CONSTRAINT "FK_83b0b6d0c00ecd2fa2688cb76a4" FOREIGN KEY ("fk_caracteristica") REFERENCES "caracteristicas"("id_caracteristica") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidades" ADD CONSTRAINT "FK_3e24462de4d836ca4a5709f77c2" FOREIGN KEY ("fk_unidad_medida") REFERENCES "unidades_medida"("id_unidad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rutas" ADD CONSTRAINT "FK_a97abdad35a72da8da3be972021" FOREIGN KEY ("fk_modulo") REFERENCES "modulos"("id_modulo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permisos" ADD CONSTRAINT "FK_201e212c6b7ce88de3b1d9d0799" FOREIGN KEY ("fk_ruta") REFERENCES "rutas"("id_ruta") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ADD CONSTRAINT "FK_a06c4f160e4c589da93f7c191bf" FOREIGN KEY ("fk_permiso") REFERENCES "permisos"("id_permiso") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ADD CONSTRAINT "FK_ba15da702a0f5d500588c597a9d" FOREIGN KEY ("fk_rol") REFERENCES "roles"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD CONSTRAINT "FK_77a0ebfb81a5cb8e3852c75e0a8" FOREIGN KEY ("fk_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_2debd80fc8ffea2584356b81313" FOREIGN KEY ("fk_rol") REFERENCES "roles"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos" ADD CONSTRAINT "FK_9e4cbcfb59dc5e94a41bd5236eb" FOREIGN KEY ("fk_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos" ADD CONSTRAINT "FK_5f51c9b480d95e189cb0a7dbd43" FOREIGN KEY ("fk_unidad") REFERENCES "unidades"("id_unidad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materias_primas" ADD CONSTRAINT "FK_117a2b43555d42d089c02b61832" FOREIGN KEY ("fk_unidad_medida") REFERENCES "unidades_medida"("id_unidad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "materias_primas" DROP CONSTRAINT "FK_117a2b43555d42d089c02b61832"`);
        await queryRunner.query(`ALTER TABLE "movimientos" DROP CONSTRAINT "FK_5f51c9b480d95e189cb0a7dbd43"`);
        await queryRunner.query(`ALTER TABLE "movimientos" DROP CONSTRAINT "FK_9e4cbcfb59dc5e94a41bd5236eb"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_2debd80fc8ffea2584356b81313"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP CONSTRAINT "FK_77a0ebfb81a5cb8e3852c75e0a8"`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" DROP CONSTRAINT "FK_ba15da702a0f5d500588c597a9d"`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" DROP CONSTRAINT "FK_a06c4f160e4c589da93f7c191bf"`);
        await queryRunner.query(`ALTER TABLE "permisos" DROP CONSTRAINT "FK_201e212c6b7ce88de3b1d9d0799"`);
        await queryRunner.query(`ALTER TABLE "rutas" DROP CONSTRAINT "FK_a97abdad35a72da8da3be972021"`);
        await queryRunner.query(`ALTER TABLE "unidades" DROP CONSTRAINT "FK_3e24462de4d836ca4a5709f77c2"`);
        await queryRunner.query(`ALTER TABLE "unidades" DROP CONSTRAINT "FK_83b0b6d0c00ecd2fa2688cb76a4"`);
        await queryRunner.query(`ALTER TABLE "unidades" DROP CONSTRAINT "FK_e78facb89f7e11b9f8b7aab9b6a"`);
        await queryRunner.query(`ALTER TABLE "unidades_medida" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "unidades_medida" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lotes" ALTER COLUMN "cantidad_unidades" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_inventario" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_total" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_alianza" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_degustacion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos" ALTER COLUMN "cantidad_vendida" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "requiere_accion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ALTER COLUMN "leido" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permisos" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permisos" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rutas" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rutas" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rutas" ALTER COLUMN "listed" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "modulos" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modulos" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "caracteristicas" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "caracteristicas" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "caracteristicas" ALTER COLUMN "estado" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventarios" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventarios" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventarios" ALTER COLUMN "estado" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_lote_materia_prima_fk_materia_prima" ON "lote_materia_prima" ("fk_materia_prima") `);
        await queryRunner.query(`CREATE INDEX "idx_lote_materia_prima_fk_lote" ON "lote_materia_prima" ("fk_lote") `);
        await queryRunner.query(`CREATE INDEX "idx_movimientos_fk_lote" ON "movimientos" ("fk_lote") `);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_fk_rol" ON "usuarios" ("fk_rol") `);
        await queryRunner.query(`CREATE INDEX "idx_notificaciones_fk_usuario" ON "notificaciones" ("fk_usuario") `);
        await queryRunner.query(`CREATE INDEX "idx_rol_permiso_fk_permiso" ON "rol_permiso" ("fk_permiso") `);
        await queryRunner.query(`CREATE INDEX "idx_rol_permiso_fk_rol" ON "rol_permiso" ("fk_rol") `);
        await queryRunner.query(`CREATE INDEX "idx_permisos_fk_ruta" ON "permisos" ("fk_ruta") `);
        await queryRunner.query(`CREATE INDEX "idx_rutas_fk_modulo" ON "rutas" ("fk_modulo") `);
        await queryRunner.query(`CREATE INDEX "idx_unidades_fk_lote" ON "unidades" ("fk_lote") `);
        await queryRunner.query(`ALTER TABLE "materias_primas" ADD CONSTRAINT "materias_primas_fk_unidad_medida_fkey" FOREIGN KEY ("fk_unidad_medida") REFERENCES "unidades_medida"("id_unidad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lote_materia_prima" ADD CONSTRAINT "lote_materia_prima_fk_lote_fkey" FOREIGN KEY ("fk_lote") REFERENCES "lotes"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lote_materia_prima" ADD CONSTRAINT "lote_materia_prima_fk_materia_prima_fkey" FOREIGN KEY ("fk_materia_prima") REFERENCES "materias_primas"("id_materia_prima") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos" ADD CONSTRAINT "movimientos_fk_lote_fkey" FOREIGN KEY ("fk_lote") REFERENCES "lotes"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos" ADD CONSTRAINT "movimientos_fk_usuario_fkey" FOREIGN KEY ("fk_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos" ADD CONSTRAINT "movimientos_fk_unidad_fkey" FOREIGN KEY ("fk_unidad") REFERENCES "unidades"("id_unidad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_fk_rol_fkey" FOREIGN KEY ("fk_rol") REFERENCES "roles"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD CONSTRAINT "notificaciones_fk_usuario_fkey" FOREIGN KEY ("fk_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ADD CONSTRAINT "rol_permiso_fk_permiso_fkey" FOREIGN KEY ("fk_permiso") REFERENCES "permisos"("id_permiso") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ADD CONSTRAINT "rol_permiso_fk_rol_fkey" FOREIGN KEY ("fk_rol") REFERENCES "roles"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permisos" ADD CONSTRAINT "permisos_fk_ruta_fkey" FOREIGN KEY ("fk_ruta") REFERENCES "rutas"("id_ruta") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rutas" ADD CONSTRAINT "rutas_fk_modulo_fkey" FOREIGN KEY ("fk_modulo") REFERENCES "modulos"("id_modulo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidades" ADD CONSTRAINT "unidades_fk_lote_fkey" FOREIGN KEY ("fk_lote") REFERENCES "lotes"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unidades" ADD CONSTRAINT "fk_unidades_inventario" FOREIGN KEY ("fk_inventario") REFERENCES "inventarios"("id_inventario") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "unidades" ADD CONSTRAINT "fk_unidades_caracteristica" FOREIGN KEY ("fk_caracteristica") REFERENCES "caracteristicas"("id_caracteristica") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "unidades" ADD CONSTRAINT "fk_unidades_unidad_medida" FOREIGN KEY ("fk_unidad_medida") REFERENCES "unidades_medida"("id_unidad") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
